import { expect, test } from '@playwright/test'

test('loads game resources only after start', async ({ page }) => {
  const gameRequests: string[] = []
  page.on('request', (request) => {
    if (/pixi|world\.worker|bootstrap/.test(request.url())) gameRequests.push(request.url())
  })
  await page.goto('/')
  await expect(page.getByRole('button', { name: 'English' })).toBeVisible()
  await expect(page.getByRole('button', { name: '中文' })).toBeVisible()
  await page.getByRole('button', { name: '中文' }).click()
  await expect(page.getByRole('button', { name: '进入世界' })).toBeVisible()
  await page.getByRole('button', { name: 'English' }).click()
  await expect(page.getByRole('button', { name: 'Enter the world' })).toBeVisible()
  expect(gameRequests).toHaveLength(0)
  await page.getByRole('button', { name: 'Enter the world' }).click()
  const canvas = page.locator('canvas[aria-label="Alohayo World map"]')
  await expect(canvas).toBeVisible()
  await expect(canvas).toHaveAttribute('data-character-area-ratio', '0.111111')
  await expect(canvas).toHaveAttribute('data-loaded-chunks', /[1-9]/)
  const startX = Number(await canvas.getAttribute('data-character-x'))
  await canvas.hover()
  await page.mouse.wheel(0, -900)
  await page.keyboard.down('d')
  await page.waitForTimeout(250)
  await page.keyboard.up('d')
  expect(Number(await canvas.getAttribute('data-character-x'))).toBeGreaterThan(startX)
  await page.keyboard.down('Shift')
  await page.keyboard.down('w')
  await page.waitForTimeout(100)
  await expect(canvas).toHaveAttribute('data-character-state', 'run')
  await page.waitForTimeout(150)
  await page.keyboard.up('w')
  await page.keyboard.up('Shift')
  await page.keyboard.press('e')
  await expect(canvas).toHaveAttribute('data-character-state', 'action')
  await expect(canvas).toHaveAttribute('data-discovered-chunks', /[1-9]/)
  await expect(canvas).toBeVisible()
})
