import type { LocaleCode } from '@alohayo/config'
import { getI18nCatalog } from '@alohayo/config'

const COPY: Record<LocaleCode, Record<string, string>> = {
  en: {
    HudLabel: 'Wayfinder status',
    OpenMap: 'Open world map',
    Eyebrow: 'The Wayfinder Chronicle',
    Title: 'Alohayo World',
    Intro:
      'Beyond the lantern glow, old roads wake, monsters stir, and the dungeons remember every name.',
    Enter: 'Begin journey',
    EnterDetail: 'Start a fresh field survey',
    EnterShortcut: 'ENTER',
    Continue: 'Continue journey',
    ContinueDetail: 'Return to your last safe camp',
    ContinueShortcut: 'ENTER',
    Settings: 'Settings',
    SettingsDetail: 'Tune display and controls',
    SettingsShortcut: 'M',
    SplashStatus: 'LOCAL WORLD',
    SplashSave: 'Progress stays on this device',
    SplashControlsLabel: 'Field controls',
    SplashControls: 'WASD move · Shift run · E act · M menu · H HUD · N map',
    MenuEyebrow: 'Wayfinder relic',
    MenuTitle: "Adventurer's Chronicle",
    Close: 'Close menu',
    TabJourney: 'Journey',
    TabParty: 'Party',
    TabGear: 'Relics',
    TabBestiary: 'Bestiary',
    TabMap: 'World map',
    TabSettings: 'Settings',
    PanelJourney: 'The trail records what the world has revealed—not what remains in the dark.',
    PanelParty: 'A small company is still a company. For now, the wayfinder travels at its head.',
    PanelGear: 'The road leaves its history on every useful thing you carry.',
    PanelBestiary: 'No monster earns a page until you meet it and live long enough to write.',
    PanelMap: 'A living survey drawn from the cells and frontiers you have crossed.',
    PanelSettings: 'The game UI is intentionally light; engine diagnostics remain in dev mode.',
    Region: 'Region',
    Biome: 'Biome',
    Discovered: 'Cells charted',
    Position: 'Position',
    Explorer: 'Explorer',
    State: 'State',
    Role: 'Calling',
    Wayfinder: 'Wayfinder',
    Relic: 'Relic',
    None: 'Nothing equipped',
    Seed: 'World seed',
    DiscoveredChunks: 'Frontiers charted',
    LoadedChunks: 'Nearby frontiers',
    Controls: 'Controls',
    ControlsValue: 'WASD / arrows · Shift · E / Space · M / Esc',
    Interface: 'Interface',
    InterfaceValue: 'Game mode only by default',
    HideHud: 'Hide field HUD',
    ShowHud: 'Show field HUD',
    HideMinimap: 'Hide field map',
    ShowMinimap: 'Show field map',
    ShortcutMenu: 'Journal',
    ShortcutHud: 'HUD',
    ShortcutMinimap: 'Map',
    Bestiary: 'Field notes',
    BestiaryEmpty: 'The ink is dry. Something is waiting beyond the fog.',
  },
  'zh-CN': {
    HudLabel: '引路人状态',
    OpenMap: '打开世界地图',
    Eyebrow: '引路人纪事',
    Title: 'Alohayo World',
    Intro: '灯火之外，古道苏醒，魔物蠢动，而地牢仍记得每一个名字。',
    Enter: '踏上旅途',
    EnterDetail: '开始一段全新的勘察',
    EnterShortcut: '回车',
    Continue: '继续旅途',
    ContinueDetail: '回到上一次安全营地',
    ContinueShortcut: '回车',
    Settings: '设置',
    SettingsDetail: '调整显示与操作',
    SettingsShortcut: 'M',
    SplashStatus: '本地世界',
    SplashSave: '进度保存在此设备上',
    SplashControlsLabel: '野外操作',
    SplashControls: 'WASD 移动 · Shift 奔跑 · E 互动 · M 菜单 · H HUD · N 地图',
    MenuEyebrow: '引路遗物',
    MenuTitle: '冒险者纪事',
    Close: '关闭菜单',
    TabJourney: '旅程',
    TabParty: '队伍',
    TabGear: '遗物',
    TabBestiary: '魔物志',
    TabMap: '世界地图',
    TabSettings: '设置',
    PanelJourney: '旅途只记录世界已经揭示的部分，不替黑暗编造答案。',
    PanelParty: '再小的队伍也是队伍。此刻，引路人走在最前面。',
    PanelGear: '每一件好用的东西，都会留下旅途的痕迹。',
    PanelBestiary: '亲眼见过并活着回来，魔物才配在这里拥有一页。',
    PanelMap: '这张活地图由你走过的地格与边疆一点点绘成。',
    PanelSettings: '游戏界面刻意保持轻盈；引擎诊断信息只留在开发模式。',
    Region: '区域',
    Biome: '生态',
    Discovered: '已绘地格',
    Position: '位置',
    Explorer: '探索者',
    State: '状态',
    Role: '使命',
    Wayfinder: '引路人',
    Relic: '遗物',
    None: '尚未装备',
    Seed: '世界种子',
    DiscoveredChunks: '已绘边疆',
    LoadedChunks: '邻近边疆',
    Controls: '操作',
    ControlsValue: 'WASD / 方向键 · Shift · E / 空格 · M / Esc',
    Interface: '界面',
    InterfaceValue: '默认仅在游戏模式启用',
    HideHud: '隐藏冒险 HUD',
    ShowHud: '显示冒险 HUD',
    HideMinimap: '隐藏野外地图',
    ShowMinimap: '显示野外地图',
    ShortcutMenu: '纪事',
    ShortcutHud: 'HUD',
    ShortcutMinimap: '地图',
    Bestiary: '野外笔记',
    BestiaryEmpty: '墨迹尚干。迷雾之外，有什么正在等待。',
  },
}

export function getGameUiCopy(locale: LocaleCode, key: string): string {
  if (key.startsWith('Character')) {
    return getI18nCatalog(locale).characterPanel[key] ?? key
  }
  if (key.startsWith('Journal')) {
    return getI18nCatalog(locale).journal[key] ?? key
  }
  return COPY[locale][key] ?? COPY.en[key] ?? key
}
